# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|

# DEFAULT VARIABLES
  common_cpus = 1
  common_ram = 1024
  common_box = "ubuntu/jammy64"

  # DESIRED INSTANCES
  instances = [
    { name: "docker01", ip: "192.168.56.16", script: "docker01.sh"}
  ]

  # VAGRANTFILE BODY 
  instances.each do |instance|
    config.vm.define instance[:name] do |specs|
      specs.vm.network "private_network", ip: instance[:ip]
      specs.vm.hostname = instance[:name]
      specs.vm.provider "virtualbox" do |vb|
        vb.cpus = instance[:cpus] || common_cpus
        vb.memory = instance[:ram] || common_ram
        vb.gui = instance[:gui] || false
      end
      specs.vm.box = instance[:box] || common_box
      specs.vm.provision "shell", path: instance[:script]
    end  
  end
end
