# -*- mode: ruby -*-
# vi: set ft=ruby :

# DEFINIR VARIABLES GLOBALES
Vagrant.configure("2") do |config|

  common_cpus = 1
  common_ram = 1024
  common_box = "ubuntu/jammy64"

  # DEFINIR ARRAY de INSTANCIAS
  instances = [
    { name: "zmonitor01", ip: "192.168.56.16", script: "zmonitor01.sh", ram: "2048", cpus: "2" },
    { name: "db01", ip: "192.168.56.15", script: "db01.sh", box: "centos/stream9", ram: "600" },
    { name: "memcache01", ip: "192.168.56.14", script: "memcache01.sh", box: "centos/stream9", ram: "600" }, 
    { name: "rabbitmq01", ip: "192.168.56.13", script: "rabbitmq01.sh", box: "centos/stream9", ram: "600" },
    { name: "tomcat01", ip: "192.168.56.12", script: "tomcat01.sh", box: "centos/stream9", ram: "800" },
    { name: "nginx01", ip: "192.168.56.11", script: "nginx01.sh", ram: "800" }
  ]

  # DEFINIR BUCLE PARA ITERAR SOBRE EL ARRAY Y CONSTRUIR CADA INSTANCIA
  instances.each do |instance|
    config.vm.define instance[:name] do |specs|
      specs.vm.network "private_network", ip: instance[:ip]
      specs.vm.hostname = instance[:name]
      specs.vm.provider "virtualbox" do |vb|
        vb.cpus = instance[:cpus] || common_cpus
        vb.memory = instance[:ram] || common_ram
        vb.gui = instance[:gui] || false
      end
      specs.vm.box = instance[:box] || common_box
      specs.vm.provision "shell", path: instance[:script]
    end  
  end
end
